; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
boards_dir = boards

; change to T5-ePaper if you have ESP32-WROVER based device (or use 'pio run -e T5-ePaper')
default_envs = seeed_xiao_esp32s3
src_dir = src

[env:seeed_xiao_esp32s3]
platform = espressif32@^7.0.1
board = seeed_xiao_esp32s3
framework = arduino

[env]
upload_speed = 115200
monitor_speed = 115200

upload_flags = 
	--before=default_reset
	--after=hard_reset
build_flags =
	-DBOARD_HAS_PSRAM
	-DCORE_DEBUG_LEVEL=0
	-Wno-narrowing
	-DBOARD_SCREEN_COMBO=503
	-DUSE_XIAO_EPAPER_DISPLAY_BOARD_EE04
lib_deps = 
	https://github.com/Seeed-Studio/Seeed_GFX.git

    