(G-CODE GENERATED BY FLATCAM v8.994 - www.flatcam.org - Version Date: 2020/11/7)

(Name: Seeed_buttonmodule-PTH.drl_cnc)
(Type: G-code from Geometry)
(Units: MM)

(Created on Friday, 14 August 2026 at 16:37)

(This preprocessor is the default preprocessor used by FlatCAM.)
(It is made to work with MACH3 compatible motion controllers.)


(TOOLS DIAMETER: )
(Tool: 1 -> Dia: 1.1)
(Tool: 2 -> Dia: 1.2)

(FEEDRATE Z: )
(Tool: 1 -> Feedrate: 300)
(Tool: 2 -> Feedrate: 300)

(FEEDRATE RAPIDS: )
(Tool: 1 -> Feedrate Rapids: 1500)
(Tool: 2 -> Feedrate Rapids: 1500)

(Z_CUT: )
(Tool: 1 -> Z_Cut: -1.7)
(Tool: 2 -> Z_Cut: -1.7)

(Tools Offset: )
(Tool: 1 -> Offset Z: 0.0)
(Tool: 2 -> Offset Z: 0.0)

(Z_MOVE: )
(Tool: 1 -> Z_Move: 2)
(Tool: 2 -> Z_Move: 2)

(Z Toolchange: 10.0 mm)
(X,Y Toolchange: 0.0000, 0.0000 mm)
(Z Start: None mm)
(Z End: 0.5 mm)
(X,Y End: 0.0000, 0.0000 mm)
(Steps per circle: 64)
(Preprocessor Excellon: default)

(X range:    2.7000 ...   10.3000  mm)
(Y range:  -16.6500 ...   -2.6000  mm)

(Spindle Speed: 1500 RPM)
G21
G90
G94

G01 F300.00

M5
G00 Z10.0000
T1
G00 X0.0000 Y0.0000                
M6
(MSG, Change to Tool Dia = 1.1000 ||| Total drills for tool T1 = 6)
G00 Z10.0000

G01 F300.00
M03 S1500
G00 X3.2500 Y-3.1500
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X9.7500 Y-3.1500
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X9.7500 Y-7.6500
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X8.6500 Y-16.0500
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X5.1500 Y-16.0500
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X3.2500 Y-7.6500
G01 Z-1.7000
G01 Z0
G00 Z2.0000
M05
G00 Z0.50
G00 X0.0 Y0.0


G0 X0Y0
